global:
    sendAnonymousUsage: false

api:
    dashboard: true
    insecure: true

providers:
    docker:
        endpoint: "unix:///var/run/docker.sock"
        watch: true
        # If false, containers that should be routed through Traefik must set the "traefik.enable" to true.
        # https://doc.traefik.io/traefik/providers/docker/#exposedbydefault
        exposedByDefault: false

    file:
        directory: '/etc/traefik/dynamic'
        watch: true

log:
    level: INFO
    format: common

entryPoints:
    web:
        address: ":80"
        http:
            redirections:
                entryPoint:
                    to: web-secure
                    scheme: https
                    permanent: true
    web-secure:
        address: ":443"